---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: o2c
    app.kubernetes.io/name: openobserve-collector
    app.kubernetes.io/version: 0.113.0
  name: o2c-openobserve-collector
  namespace: openobserve-collector
