---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio-credentials-fetcher
  namespace: kaiwo
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: default-user
        metadataPolicy: None
        property: API_ACCESS_KEY
      secretKey: minio-access-key
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: default-user
        metadataPolicy: None
        property: API_SECRET_KEY
      secretKey: minio-secret-key
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-secret-store
  target:
    creationPolicy: Owner
    name: minio-credentials
