---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: k8s-secret-store-minio-secret
  namespace: cf-es-backend
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: default-user
        metadataPolicy: None
        property: CONSOLE_ACCESS_KEY
      secretKey: CONSOLE_ACCESS_KEY
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: default-user
        metadataPolicy: None
        property: CONSOLE_SECRET_KEY
      secretKey: CONSOLE_SECRET_KEY
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: default-user
        metadataPolicy: None
        property: API_ACCESS_KEY
      secretKey: API_ACCESS_KEY
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: default-user
        metadataPolicy: None
        property: API_SECRET_KEY
      secretKey: API_SECRET_KEY
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: minio-secret-store
  target:
    creationPolicy: Owner
    name: default-user
