---
apiVersion: v1
data:
  config.yaml: |
    controllerManager:
      health:
        bindAddress: ":8081"
      metrics:
        bindAddress: ":8443"
      leaderElection: true
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: appwrapper
    control-plane: controller-manager
  name: appwrapper-operator-config
  namespace: appwrapper-system
