---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: appwrapper
    control-plane: controller-manager
  name: appwrapper-webhook-server-cert
  namespace: appwrapper-system
