{
 "title": "GPU Overview - Multicluster",
 "description": "Overview of the system",
 "tags": [
  "GPU",
  "Metrics"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "g_gpu_uuids", "query": { "query": "label_values(GPU_UUID)" } },
   { "name": "g_job_ids", "query": { "query": "label_values(job_id)" } },
   { "name": "g_cluster_name_k8", "label": "K8 Cluster", "query": { "query": "label_values(k8s_cluster_name)" } },
   { "name": "g_org_id", "label": "Org ID", "query": { "query": "label_values(org_id)" } },
   { "name": "g_hostname", "label": "Hostname", "query": { "query": "label_values(hostname)" } }
  ]
 },
 "panels": [
  {
   "title": "Total GPUs",
   "type": "stat",
   "description": "Number of GPUs in the node",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gpu_nodes_total{k8s_cluster_name=~\"$g_cluster_name_k8\"})",
     "legendFormat": "GPUs"
    }
   ]
  },
  {
   "title": "Jobs",
   "type": "stat",
   "description": "Number of jobs",
   "gridPos": { "h": 6, "w": 2, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(group by(workload_id) (gpu_gfx_activity{k8s_cluster_name=~\"$g_cluster_name_k8\"}))",
     "legendFormat": "Jobs"
    }
   ]
  },
  {
   "title": "Total Power Usage",
   "type": "stat",
   "description": "Total power usage, in Watts",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A+$B", "type": "math" }
   ]
  },
  {
   "title": "PCIe Max Speed",
   "type": "stat",
   "description": "Current maximum PCIe speed",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_values(\"count\", pcie_max_speed{k8s_cluster_name=~\"$g_cluster_name_k8\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PCIe Counts",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(pcie_recovery_count{k8s_cluster_name=~\"$g_cluster_name_k8\"}[$__interval]))",
     "legendFormat": "Recovery"
    },
    {
     "expr": "sum(delta(pcie_replay_count{k8s_cluster_name=~\"$g_cluster_name_k8\"}[$__interval]))",
     "legendFormat": "Replay"
    },
    {
     "expr": "sum(delta(pcie_replay_rollover_count{k8s_cluster_name=~\"$g_cluster_name_k8\"}[$__interval]))",
     "legendFormat": "Replay Rollover"
    },
    {
     "expr": "sum(delta(pcie_nack_received_count{k8s_cluster_name=~\"$g_cluster_name_k8\"}[$__interval]))",
     "legendFormat": "NACK Received"
    },
    {
     "expr": "sum(delta(pcie_nack_sent_count{k8s_cluster_name=~\"$g_cluster_name_k8\"}[$__interval]))",
     "legendFormat": "NACK Sent"
    }
   ]
  },
  {
   "title": "Top 5 GPU Usage",
   "type": "stat",
   "description": "Top 5 current GPU GFX Activity, labeled with hostname, GPU ID, and job ID.",
   "gridPos": { "h": 12, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk by() (5, gpu_gfx_activity{k8s_cluster_name=~\"$g_cluster_name_k8\"})",
     "legendFormat": "{{hostname}} | {{gpu_id}} | {{job_id}}"
    }
   ]
  },
  {
   "title": "Top 5 Used VRAM",
   "type": "stat",
   "description": "Top 5 GPUs with highest VRAM used, labeled with hostname and GPU ID.",
   "gridPos": { "h": 12, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, gpu_used_vram{k8s_cluster_name=~\"$g_cluster_name_k8\"})",
     "legendFormat": "{{hostname}} | {{gpu_id}}"
    }
   ]
  },
  {
   "title": "Current Total PCIe Bandwidth",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pcie_bandwidth{k8s_cluster_name=~\"$g_cluster_name_k8\"})",
     "legendFormat": "Total current PCIe bandwidth"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gpu_used_vram{k8s_cluster_name=~\"$g_cluster_name_k8\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(gpu_total_vram{k8s_cluster_name=~\"$g_cluster_name_k8\"})",
     "legendFormat": "__auto"
    },
    { "expression": "($A / $B) * 100", "type": "math" }
   ]
  },
  {
   "title": "Allocated GPUs",
   "type": "stat",
   "description": "\\# of GPUs allocated by jobs",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(group by(gpu_uuid) (gpu_gfx_activity{k8s_cluster_name=~\"$g_cluster_name_k8\", pod!=\"\"}))",
     "legendFormat": "Allocated by Pods"
    },
    {
     "expr": "sum(group by(gpu_uuid) (gpu_gfx_activity{cluster_name=\"$g_cluster_name\"} > 0))",
     "legendFormat": "Busy GPUs"
    }
   ]
  },
  {
   "title": "Total PCIe Bandwidth",
   "type": "timeseries",
   "description": "Total PCIe Bandwidth over time",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "sum(pcie_bandwidth{k8s_cluster_name=~\"$g_cluster_name_k8\"})",
     "legendFormat": "Total PCIe Bandwidth"
    }
   ]
  },
  {
   "title": "Energy Consumed",
   "type": "stat",
   "description": "Total accumulated energy consumed",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "joule" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(gpu_energy_consumed{k8s_cluster_name=\"$g_cluster_name_k8\"}[$__interval]))",
     "legendFormat": "Accumulated Energy Consumed (nJ)"
    },
    { "expression": "$A / 1000000", "type": "math" }
   ]
  },
  {
   "title": "Average GPU Usage",
   "type": "timeseries",
   "description": "Average of current GPU GFX activity",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(gpu_gfx_activity{k8s_cluster_name=~\"$g_cluster_name_k8\"})",
     "legendFormat": "GPU Usage"
    }
   ]
  },
  {
   "title": "Used VRAM",
   "type": "timeseries",
   "description": "Used VRAM over time",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expression": "($A / $B) * 100", "type": "math" }
   ]
  },
  {
   "title": "Average GPU Power",
   "type": "timeseries",
   "description": "Average GPU package power, in Watts",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "avg(gpu_package_power{k8s_cluster_name=~\"$g_cluster_name_k8\", card_model=~\"102-G30211-00|102-G30211-0C|102-G30211-4C|102-G30212-0C|102-G30213-00|102-G30213-0C\"})",
     "legendFormat": "GPU Power"
    },
    {
     "expr": "avg(gpu_average_package_power{k8_cluster_name=~\"$g_cluster_name_k8\", card_model!~\"102-G30211-00|102-G30211-0C|102-G30211-4C|102-G30212-0C|102-G30213-00|102-G30213-0C\"})",
     "legendFormat": "GPU Power"
    }
   ]
  },
  {
   "title": "Average GPU Temperature",
   "type": "timeseries",
   "description": "Current temperature, in Celsius",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg(gpu_edge_temperature{card_model!~\"102-G30211-00|102-G30211-0C|102-G30211-4C|102-G30212-0C|102-G30213-00|102-G30213-0C\", k8_cluster_name=~\"$g_cluster_name_k8\"})",
     "legendFormat": "Edge Temperature"
    },
    {
     "expr": "avg(gpu_junction_temperature{card_model=~\"102-G30211-00|102-G30211-0C|102-G30211-4C|102-G30212-0C|102-G30213-00|102-G30213-0C\", k8s_cluster_name=~\"$g_cluster_name_k8\"})",
     "legendFormat": "Junction Temperature"
    }
   ]
  },
  {
   "title": "Average Memory Temperature",
   "type": "timeseries",
   "description": "Current memory temperature, in Celsius",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg(gpu_memory_temperature{k8s_cluster_name=~\"$g_cluster_name_k8\"})",
     "legendFormat": "Memory Temperature"
    }
   ]
  },
  {
   "title": "Average Sensor Temperatures",
   "type": "timeseries",
   "description": "Average current temperatures, in Celsius, from:\n- HBM (4 sensors)\n- Edge\n- Junction/hotspot",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg(gpu_hbm_temperature{k8s_cluster_name=~\"$g_cluster_name_k8\"})",
     "legendFormat": "HBM Temperature"
    },
    {
     "expr": "avg(gpu_edge_temperature{k8s_cluster_name=~\"$g_cluster_name_k8\"})",
     "legendFormat": "Edge Temperature"
    },
    {
     "expr": "avg(gpu_junction_temperature{k8s_cluster_name=~\"$g_cluster_name_k8\"})",
     "legendFormat": "Junction Temperature"
    }
   ]
  },
  {
   "title": "All GPUs",
   "type": "table",
   "description": "List of all GPUs. Click on the row to go to that GPU's dashboard (opens new tab).",
   "gridPos": { "h": 16, "w": 16, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "gpu_gfx_activity{k8s_cluster_name=~\"$g_cluster_name_k8\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}