{
 "title": "MinIO simple dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "g_cluster_name_k8s", "label": "K8S Cluster", "query": { "query": "label_values(k8s_cluster_name)" } }
  ]
 },
 "panels": [
  {
   "title": "Cluster Free Capacity (%)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(minio_cluster_capacity_usable_free_bytes{job=\"minio-cluster-metrics\", k8s_cluster_name=~\"$g_cluster_name_k8s\"} * 100) / minio_cluster_capacity_usable_total_bytes{job=\"minio-cluster-metrics\", k8s_cluster_name=\"$g_cluster_name_k8s\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Drive Used Bytes",
   "type": "timeseries",
   "description": "Used bytes on a drive",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "minio_node_drive_used_bytes{job=\"minio-resource-metrics\", k8s_cluster_name=\"$g_cluster_name_k8s\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Drive Total Bytes",
   "type": "stat",
   "description": "Total bytes on a drive",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minio_node_drive_total_bytes{job=\"minio-resource-metrics\", k8s_cluster_name=\"$g_cluster_name_k8s\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Drive Used Bytes",
   "type": "stat",
   "description": "Used bytes on a drive",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minio_node_drive_used_bytes{job=\"minio-resource-metrics\", k8s_cluster_name=\"$g_cluster_name_k8s\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "minio_bucket_usage_total_bytes",
   "type": "gauge",
   "description": "Total bucket size in bytes",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minio_bucket_usage_total_bytes{k8s_cluster_name=\"$g_cluster_name_k8s\"}",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Total Number of Buckets",
   "type": "stat",
   "description": "Total number of buckets in the cluster",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "buckets" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minio_cluster_bucket_total{job=\"minio-cluster-metrics\", k8s_cluster_name=~\"$g_cluster_name_k8s\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Bucket Usage Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "minio_bucket_usage_total_bytes{k8s_cluster_name=\"$g_cluster_name_k8s\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}